# https://numtide.github.io/devshell
[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[[commands]]
package = "nodejs"
help = "Node.js"

[[commands]]
package = "nodePackages.expo-cli"
help = "Expo CLI"

